const names = [
  'jones',
  'fred',
  'leonard',
  'beatrice',
  'sasha',
  'penelope',
  'giovanna',
  'titus',
  'imperialdestroyer',
  'orange',
  'apple',
  'abigail',
  'taco',
  'gerald',
  'jenkins',
  'xerlapta',
  'vareyla',
  'rich',
  'ava',
  'justin',
  'luke',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const email = [
  'george@frank.com',
  'bigjones@waffle.com',
  'elliot45@james.com',
  'quong@quong.com',
  'frankiebigslick@woah.com',
  'bestcat@dog.com',
  'wizardsarereal@magic.com',
  'giantoctopus@tentacle.com',
  'wiggysligs@pabalasta@com',
  'wowweee@wiggle.com',
'snicolas@bashirian.org',
'qbins@gmail.com',
'kuhlman.tara@abernathy.com',
'ricardo01@yahoo.com',
'sporer.lesley@hotmail.com',
'akihn@carter.org',
'kuhic.seth@hotmail.com',
'sheldon09@weissnat.com',
'flarson@kuhlman.com',
'watsica.aileen@gmail.com',
'maddison50@gmail.com',
'rodriguez.karen@davis.net',
'nicolas.art@gmail.com',
'pklocko@yahoo.com',
'mozelle75@gmail.com',
'bernice60@reinger.org',
'martina35@yahoo.com',
'maybelle.murphy@gmail.com',
'waylon.aufderhar@hotmail.com',
'homenick.nicholas@bruen.com',
'shaina35@gmail.com',
'cathy.kuhn@mcdermott.biz',
'walsh.jermaine@hotmail.com',
'ufisher@cruickshank.com',
'bdurgan@streich.com',
'joey64@jakubowski.com',
'kzieme@gmail.com',
'blanche.nitzsche@paucek.info',
'yesenia.johns@daugherty.com',
'mazie38@gmail.com',
'kroob@lemke.com',
'leonie53@leuschke.com',
'reina33@sporer.org',
'chyna.cormier@yahoo.com',
'olson.earline@auer.net',
'corkery.grant@watsica.org',
'lubowitz.carmelo@hotmail.com',
'williamson.aron@yahoo.com',
'roberts.joe@boehm.com',
'elouise.abshire@murphy.info',
'ggutkowski@hotmail.com',
'tromp.marshall@schaefer.biz',
'george44@mcdermott.com',
'prince22@hegmann.info',
'hailee.mante@shields.org',
'kendall.shanahan@fay.info',
'kschiller@hauck.com',
'grimes.estelle@leannon.org',
'aurore.williamson@vonrueden.info',
'konopelski.eliza@yahoo.com',
'moen.jacynthe@mraz.com',
'aric.krajcik@bechtelar.com',
'rowe.roselyn@bernier.com',
'ray.lemke@hotmail.com',
'jkerluke@yahoo.com',
'billie.larson@harvey.com',
'dmacejkovic@yahoo.com',
'krajcik.malcolm@gmail.com',
'alesch@nitzsche.biz',
'lilian.stark@gmail.com',
'mckenzie90@hotmail.com',
'dkirlin@fisher.biz',
'christelle36@williamson.com',
'yazmin.mills@kris.com',
'julian81@yahoo.com',
'vernice29@hotmail.com',
'mann.kira@hotmail.com',
'mcdermott.fidel@batz.info',
'balistreri.laverna@harris.org',
'ullrich.joseph@beer.info',
'jennyfer.bernhard@gmail.com',
'naomie.torphy@hotmail.com',
'fgraham@hotmail.com',
'osatterfield@hagenes.com',
'barbara.nienow@schinner.net',
'saufderhar@gmail.com',
'lind.roel@emmerich.com',
'kozey.teagan@harber.com',
'breanna.hudson@wiegand.biz',
'skovacek@yahoo.com',
'bortiz@ratke.com',
'sim.runte@koepp.com',
'wisozk.leanna@yahoo.com',
'alittel@hotmail.com',
'dtreutel@yahoo.com',
'cbednar@hotmail.com',
'alberta.davis@hotmail.com',
'pstroman@gmail.com',
'pollich.alana@predovic.com',
'rhiannon87@rodriguez.com',
'judy70@white.com',
'jamal02@gerlach.biz',
'kyla81@hotmail.com',
'sbatz@gmail.com',
'hackett.immanuel@mcclure.com',
'ygerlach@gmail.com',
'marcelle30@yahoo.com',
'rutherford.freddy@yahoo.com',
'gshanahan@hotmail.com',
'jonatan.douglas@rempel.com',	
]

const thought = [
  'thats great, holy smokes',
  'this wiggles my endorphins',
  'wow, what a bubbs spuggly',
  'holy bananas thats pasta',
  'wiggles on wiggles my friend',
  'this makes me me feel great, like a nice bath',
  'woah now, thats honkin',
  'holy spubbubs thats jones',
  'wigglebiscuit century',
  'celery waffle justic',
  'yeahhhh this is so dope',
  'fusion the ice cream',
  'neapolitan surprise',
  'three flavors you name em',
  'big city status',
  'excellent my dude',
  'big frankies',
  'lemon is a citrus fruit',
];

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random full name
const getRandomName = () =>
  `${getRandomArrItem(names)}`;

const getRandomEmail = () =>
  `${getRandomArrItem(email)}`;

// Function to generate random assignments that we can add to student object.
const getRandomThoughts = () => {
  `${getRandomArrItem(thought)}`;
};

// Export the functions for use in seed.js
module.exports = { getRandomName, getRandomEmail, getRandomThoughts };
